### ISSUE TITLE
Wefax schedule update

### ISSUE THREAD

**Issue by tchiwam** [seandepagnier/weatherfax_pi#106]
I just received these 2 wefax from DE, if you want to attach them to your project and/or update the xml description
![wefax_20180817_150319_3854100_nocorr](https://user-images.githubusercontent.com/22383701/44273444-0cfefc00-a22f-11e8-8ce9-0f9f73601709.png)

![wefax_20180817_144355_3853800_nocorr](https://user-images.githubusercontent.com/22383701/44273445-0cfefc00-a22f-11e8-87e7-1ae63ff4bba2.png)

Thank you for the great plugin.

**Comment by seandepagnier** [comment]
the hamburg station is already in the schedule list.

**Comment by rgleason** [comment]
That is helpful, but it is always easier to have digital text.

**Comment by tchiwam** [comment]
These are the schedules coming with the receiver on 
14:25UT 
14:45UT

I noticed these are missing, might be good to map this in a piece of land.

**Comment by rgleason** [comment]
Please explain this more completely. I can make the change if necessary, but I need complete information to so. What exactly is needed.

**Comment by rgleason** [comment]
This schedule needs to be converted to a text file first and then attached to this Issue so it can be used.

**Comment by rgleason** [comment]
I will compare these png's to the current NOAA world wide schedule and make adjustments. This can be closed now.  Thank you.  OP should close.
