### ISSUE TITLE
User information

### ISSUE THREAD

**Issue by ptulp** [seandepagnier/weatherfax_pi#16]
Sean,

How can we inform the user that for OSX the portaudio libraries should be installed.
Otherwise the plugin would not show up and cause unnecessary problems.
For OSX this would be by the  "brew install portaudio" command in a terminal window.
Should we mention this on the download page of the plugin??

Peter

**Comment by nohal** [comment]
Peter...
We should find a way to install the library with the plugin - it is unrealistic to expect the users being able to install anything manually. As we bitterly realized over the time...

Pavel

**Comment by ptulp** [comment]
Pavel,
The problem is that I am not sure there one libportaudio that fits all OSX versions.
I cannot find a download of a compiled library for OSX. All procedures I find do a download of the source and do a compile/install.
We could do a check if the library is present before installing the package with a procedure of how to
install the library and stop the install if not present.
That would at least prevent the plugin not showing up in openCPN as it would not load the plugin.

Peter

**Comment by seandepagnier** [comment]
Are you serious that one libportaudio can't fit all versions?  Why not?  We could make the plugin dlopen portaudio and then if that fails it can still work without capture support.

**Comment by ptulp** [comment]
This is just an assumption as I cannot find a precompiled library anywhere.
As I don't have multiple OSX machines I cannot test this.

I have made a small change to the buildosx/InstallOSX/weatherfax_pi.pkgproj.in file which will display
the following message if the library is not found:

Please install PortAudio. 
Install Homebrew, following the instructions on http://brew.sh. 
Install portaudio with command: brew install portaudio in a terminal window

It then aborts the installation.
If we use your dlopen solution then probably all OSX users will miss the capture function and there will be questions about it so then we need to mention this somewhere.

**Comment by seandepagnier** [comment]
Could you instead just take the library distributed with homebrew, and include it in the package?

**Comment by nohal** [comment]
As far as I can tell we should be good just packaging the dylib (which has to be built targeting 10.7 as all the other stuff we distribute)

**Comment by ptulp** [comment]
OK, after more searching I found a 10.7 portaudio library.
It seems to work if I replace my original libraries with it.
So now I need to include it in the OSX install file.
Where should we place the lib file. Create a directory libs or images?

**Comment by nohal** [comment]
I suppose there is a standard location (where the wx dylibs are placed by the OpenCPN package) or maybe next to the _pi dylib. I know close to nothing about how the OS X app bundles work though.

**Comment by ptulp** [comment]
I was more wondering where to put the source not the destination.
Can we put this source library here in github or is that not the place?

**Comment by nohal** [comment]
I thought you talk about a dylib already built for 10.7... If it is source, different from upstream and "hard" to find, just create a github repo for it.
If it really is a prebuilt dylib, place it on http://sourceforge.net/projects/opencpnplugins/ and we will mention it in the README (we use the same procedure for the libraries needed on windows already). During packaging, it should be in the build directory (or maybe in buildosx, we just have to reflect it in the packaging instructions).

**Comment by ptulp** [comment]
OK, so because this is for weatherfax I should put it in http://sourceforge.net/projects/opencpnplugins/files/weatherfax_pi/   Right?

**Comment by nohal** [comment]
Yes, please.

**Comment by lanceberc** [comment]
I used ports to install portaudio on OSX Yosemite ("sudo port install portaudio") - this might be easier than brew for some people. Document both?

How hard would it be to disable this feature if portaudio isn't present? Do you think a significant fraction of OpenCPN users will be able to hook a shortwave/SSB radio to their computer?

**Comment by nohal** [comment]
The majority of normal users is not able to use either. As we can package the dylib for them, there should be no problem.

**Comment by ptulp** [comment]
I made an update to include the library in the package.
Also put a zip file with the header and library files on sourceforge for download before a compile and packaging

**Comment by lanceberc** [comment]
I was able to use the sourceforge package to build/install the plugin on OSX-10.10.

I have notes for my install experience, but the forum system has decided that I'm suspicious and won't let me post. A tad frustrating.

**Comment by rgleason** [comment]
lanceberc, can you send these notes to me, I will attach.  You have my email I believe (PM)

**Comment by lanceberc** [comment]
Have lost your PM, but asked for it in message on CF.

**Comment by rgleason** [comment]
lanceberc, have you perhaps seen these notes for Mac install of wxfax_pi?
I can include them somehow in documentation?

**Comment by rgleason** [comment]
Can this be closed now? Is better documentation really needed? I believe what is needed should be in the  readme.

**Comment by lanceberc** [comment]
I'd updated the Mac build notes a few summers ago but I don't think anyone has maintained them since.

**Comment by rgleason** [comment]
Lanceberc,
Would you like to attach them to here, we can include them in the README.

**Comment by rgleason** [comment]
Peter,
Can this be closed now?  I think you guys resolved it.  Thanks.

**Comment by nohal** [comment]
Did we? How? If you refer to my latest PR, it did nothing about this issue.

**Comment by ptulp** [comment]
Rick,

Pavel is right, there are still issues with it.

Peter

**Comment by nohal** [comment]
I hope https://github.com/seandepagnier/weatherfax_pi/pull/85/commits/2fc36396591fd8583abbf9aa90cb0e1afd67f3aa solves this.

**Comment by rgleason** [comment]
Have any Mac Users had a chance to test Pavel's improvements? If so, can this be closed now?  Sean has accepted the PR.
