### ISSUE TITLE
Image Wizard - How to rotate a Polar?

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weatherfax_pi#32]
I am using v 4.2   weatherfax 5001 from opencpn.org downloads.

How do we rotate this polar first so that we can apply the polar coords?

I am trying to update NOAA - Boston weatherfax  Thanks.
![polar-how-to-rotate](https://cloud.githubusercontent.com/assets/2363959/17590796/25dd6146-5fa9-11e6-85bb-242e3aa454ad.png)

**Comment by seandepagnier** [comment]
you should be able to go back to the first step and set the rotation

**Comment by rgleason** [comment]
Got it. Dumb.  It just popped up there and I assumed it was at the first screen. Sorry.

Closing
